### ISSUE TITLE
Страница городов с группировкой по областям

### ISSUE THREAD

**Issue by nicothin** [nicothin/akinita#4]
Макет: https://www.figma.com/file/m7tbooJfqSTppw57xfapCe/%D0%9B%D0%B8%D1%87%D0%BD%D1%8B%D0%B9-%D0%BA%D0%B0%D0%B1%D0%B8%D0%BD%D1%82%D0%B5%2F-Payment-flow?node-id=91%3A46

Речь про:

![image](https://user-images.githubusercontent.com/3499680/166468833-237f9aa6-d2c4-4b8b-8897-823160201476.png)

Вёрстка: пока не выполнена, см. вопросы.

Вопросы:

1. как выглядит мобильная версия?
2. если сущностей много, как мне найти искомое?

@vladimir075 @greeceruit @nadezdafrolova

**Comment by nadezdafrolova** [comment]
1. Мобильная версия связка

Все Регионы - https://www.figma.com/file/m7tbooJfqSTppw57xfapCe/%D0%9B%D0%B8%D1%87%D0%BD%D1%8B%D0%B9-%D0%BA%D0%B0%D0%B1%D0%B8%D0%BD%D1%82%D0%B5%2F-Payment-flow?node-id=1628%3A8933

Отдельный регион + номосы - 
https://www.figma.com/file/m7tbooJfqSTppw57xfapCe/%D0%9B%D0%B8%D1%87%D0%BD%D1%8B%D0%B9-%D0%BA%D0%B0%D0%B1%D0%B8%D0%BD%D1%82%D0%B5%2F-Payment-flow?node-id=1812%3A7077

Муниципалитеты - 
https://www.figma.com/file/m7tbooJfqSTppw57xfapCe/%D0%9B%D0%B8%D1%87%D0%BD%D1%8B%D0%B9-%D0%BA%D0%B0%D0%B1%D0%B8%D0%BD%D1%82%D0%B5%2F-Payment-flow?node-id=1812%3A7243

**Comment by nadezdafrolova** [comment]
2. Поиска не будет

**Comment by nicothin** [comment]
@nadezdafrolova

> Все Регионы - https://www.figma.com/file/m7tbooJfqSTppw57xfapCe/%D0%9B%D0%B8%D1%87%D0%BD%D1%8B%D0%B9-%D0%BA%D0%B0%D0%B1%D0%B8%D0%BD%D1%82%D0%B5%2F-Payment-flow?node-id=1628%3A8933

Открываю, вижу такую картинку. Куда смотреть не ясно.
![image](https://user-images.githubusercontent.com/3499680/166985119-2d461944-6524-4e8f-98bf-6f01458d9de4.png)



> Отдельный регион + номосы - https://www.figma.com/file/m7tbooJfqSTppw57xfapCe/%D0%9B%D0%B8%D1%87%D0%BD%D1%8B%D0%B9-%D0%BA%D0%B0%D0%B1%D0%B8%D0%BD%D1%82%D0%B5%2F-Payment-flow?node-id=1812%3A7077
> 
> Муниципалитеты - https://www.figma.com/file/m7tbooJfqSTppw57xfapCe/%D0%9B%D0%B8%D1%87%D0%BD%D1%8B%D0%B9-%D0%BA%D0%B0%D0%B1%D0%B8%D0%BD%D1%82%D0%B5%2F-Payment-flow?node-id=1812%3A7243

На настольном страница одна, на мобилке несколько? Это не то чтобы нереально, но неоправданно дорого и ненадежно.
Видимо, я просто не понимаю как это должно работать.
Можете объяснить в макете или текстовым описанием со скринами?

**Comment by nicothin** [comment]
Закрываю, ибо выяснилось, что это часть https://github.com/nicothin/akinita/issues/3
